### ISSUE TITLE
Ctrl+C to copy full text shows up twice under DetailedSummary

### ISSUE THREAD

**Issue by davkean** [KirillOsenkov/MSBuildStructuredLog#1]
![image](https://cloud.githubusercontent.com/assets/1103906/15236901/1fa70d94-187e-11e6-8da2-3bdedb45e5d3.png)

**Comment by KirillOsenkov** [comment]
This is currently by design. These are two multiline messages, each one starts with an empty line, but has different contents. The trimming algorithm results in what you're seeing above.

Long term I'm thinking to properly parse DetailedSummary or write better summary myself and present this properly as a UIElement with charts etc.
