### ISSUE TITLE
Detect (and log) file accesses/reads/writes

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#104]
From @tmat: Is there a way to find out what task wrote to/created a specific file?

**Comment by KirillOsenkov** [comment]
I wonder if @rainersigwald has any ideas about this.

**Comment by rainersigwald** [comment]
Not externally 😇.

To elaborate a bit: we do have an internal tool that does this, but it can't be released externally because it takes a (source-level) dependency on an internal-only library. It's implemented by hooking syscalls that do I/O operations and adding a layer to them that logs the paths, in conjunction with a logger that tracks the current project/target/task tuple.

Unfortunately, that's not easy to implement . . .
