### ISSUE TITLE
Enable viewing source for skipped targets

### ISSUE THREAD

**Issue by dsplaisted** [KirillOsenkov/MSBuildStructuredLog#117]
It's great being able to easily jump to the source code for a target, but it would be nice if it also worked for skipped targets.

- Open a .binlog file
- Navigate to a target that was skipped
- Right click on target

EXPECTED: Option to view the source of the target
ACTUAL: No option to view source of the target

![image](https://user-images.githubusercontent.com/145043/29983199-9f55bc90-8f09-11e7-9f70-14dfbf9f0895.png)

**Comment by KirillOsenkov** [comment]
Skipped targets are never reported to us by MSBuild, we never receive anything at all. All we have is the target name which is inferred because it is mentioned in BeforeTargets, AfterTargets, DependsOnTargets of other targets. Just given a name of a target I don't know how to find it's location in source.

Perhaps a full-text search of all included files for <Target Name="MyName?

**Comment by KirillOsenkov** [comment]
Actually never mind, I might be confused... I'll take a look. Maybe the location is mentioned in the message that says "Target skipped".

**Comment by chipplyman** [comment]
I think the issue is more subtle than 'skipped items'.

In this screenshot, only the BuildOnlySettings and BeforeBuild targets accept navigation.  The parent Build and CoreBuild tasks notably do not.

![image](https://user-images.githubusercontent.com/32884183/31689532-8aaee5e6-b344-11e7-9182-9bb53301ac21.png)

**Comment by KirillOsenkov** [comment]
See https://github.com/Microsoft/msbuild/issues/2751

**Comment by KirillOsenkov** [comment]
@panopticoncentral has fixed this and I've verified that it is now working great with the latest MSBuild. We now consume the TargetSkippedEventArgs.
