### ISSUE TITLE
NullReferenceException when creating log from app

### ISSUE THREAD

**Issue by bording** [KirillOsenkov/MSBuildStructuredLog#150]
If I open a solution and run it directly from the app, the resulting log file is full of the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Logging.StructuredLogger.ItemGroupParser.ParsePropertyOrItemList(String message, String prefix, StringCache stringTable) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\ItemGroupParser.cs:line 30
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.AddItemGroup(BuildMessageEventArgs args, String prefix, NamedNode containerNode) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\MessageProcessor.cs:line 154
   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.Process(BuildMessageEventArgs args) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\MessageProcessor.cs:line 46
   at Microsoft.Build.Logging.StructuredLogger.Construction.MessageRaised(Object sender, BuildMessageEventArgs args) in C:\MSBuildStructuredLog\src\StructuredLogger\Construction\Construction.cs:line 345
```

If I use the Build Logging window from inside VS, the resulting log files from the same project appear to be fine.

[logs.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/1604552/logs.zip)

**Comment by KirillOsenkov** [comment]
I think you're using the app version 1.1.194. File -> Start Page will show the version in the top right corner.

Make sure it's 1.1.221. Just start the app from the start screen (Windows + "MSB" will find it) and let it update.

If that still reproduces, could you build the app from source and tell me what variable exactly is null for you? I can't reproduce this.

**Comment by bording** [comment]
Sorry, should have included the app version in the original post. I'm using 1.1.221 and seeing this error.

Are you saying that the `broken.buildlog` I attached doesn't show the exceptions for you?

**Comment by bording** [comment]
Actually capturing the exception seems to be difficult, because whatever error is happening is causing breakpoints to not be hit!

**Comment by KirillOsenkov** [comment]
Oh, this is because the exception actually happens inside MSBuild! It's a different process.

To debug this, you need to copy the exact command line passed to MSBuild:

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\Brandon\Documents\Visual Studio 2017\Projects\ConsoleApp59\ConsoleApp59.sln" /t:Rebuild /v:diag /nologo /noconlog /logger:StructuredLogger,"C:\Users\Brandon\AppData\Local\MSBuildStructuredLogViewer\app-1.1.221\StructuredLogger.dll";"C:\Users\Brandon\AppData\Local\Temp\MSBuildStructuredLog-4624.buildlog"
```

Then open a new Visual Studio, File -> Open -> Project/Solution, then open `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` as a project. Then right-click on MSBuild in Solution Explorer, it will let you specify the arguments and working directory. Paste these arguments (without msbuild.exe) and your working directory (C:\Users\Brandon\Documents\Visual Studio 2017\Projects\ConsoleApp59), enable first-chance exceptions (Debug -> Windows -> Exception Settings), then just F5. You should be able to see the exception and what exactly is null.

broken.buildlog shows the exceptions for me, but it's a record of the exceptions that happened during the build in the MSBuild.exe process. These exceptions actually aren't raised, they're just records. To catch and debug these exceptions you need to debug the MSBuild process.

**Comment by KirillOsenkov** [comment]
OH! Apparently I'm running into this:
https://stackoverflow.com/questions/18086235/initializing-threadstatic-field-still-causes-nullreferenceexception

**Comment by KirillOsenkov** [comment]
Could you try with https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/f743ef5ec1a598bd557a0c788f17dca9c2131cc1 and see if it goes away?

**Comment by bording** [comment]
> Oh, this is because the exception actually happens inside MSBuild! It's a different process.

Oh, of course. `ItemGroupParser` is part of the logger, so that would explain why I wasn't hitting a breakpoint when opening the log. That would also explain why the binlog from VS didn't have the problem either.

> Could you try with f743ef5 and see if it goes away?

That appears to have fixed it!

**Comment by KirillOsenkov** [comment]
Pushed a new release. Thanks for investigating this!
