### ISSUE TITLE
cannot view contents of '.metaproj' projects?

### ISSUE THREAD

**Issue by japj** [KirillOsenkov/MSBuildStructuredLog#158]
With v1.2.5 of MSBuild Structured Log Viewer (and v1.1.224.247 of StructuredLogger.dll):

We seem to have some .metaproj Projects in our binlog (not sure exactly what is causing that, but it seems to happen to both csproj and vcxproj files).

Double click in the log will not show the "content" of the .metaproj (or the representation).
It will just expand/collapse the tree view instead.

**Comment by KirillOsenkov** [comment]
.metaproj files are temporary generated projects the represent solutions. Since MSBuild doesn't natively understand .sln format, it translates it to a corresponding MSBuild "metaproj" on disk, then builds that, and deletes the .metaproj. I'm guessing by the time the logger wants to read the .metaproj from disk to embed it, the file already is deleted.

Try setting the environment variable MSBUILDEMITSOLUTION=1 (e.g. in command prompt via `set MSBUILDEMITSOLUTION=1` and then build again from that prompt). It should leave the .metaproj on disk.

**Comment by japj** [comment]
Thank you, that indeed solved the problem.
For some reason we also have metaproj files for some of the project files (not only the solution) so that confused me a bit.
