### ISSUE TITLE
View Pane Missing

### ISSUE THREAD

**Issue by BihtSift** [KirillOsenkov/MSBuildStructuredLog#171]
I seemed to have gotten into a state where the view pane is completely missing.  I can't view project exports, command lines, etc.

I'm not sure how I got into this state, but I know it happened the day after I was working remotely.  Or perhaps it was removed?

Perhaps there's a preferences file I can delete to force a reset?

**Comment by KirillOsenkov** [comment]
Can you include a screenshot? What is the app version you're using? It should be 1.2.12 (shown in the top right corner after the app starts).

Did you restart the app? 

Do you have the file `%localappdata%\Microsoft\MSBuildStructuredLog\LoggerExceptions.txt`? If so, can you paste the contents here?

**Comment by BihtSift** [comment]
I installed the latest version and that fixed me up.   I was on Version: 1.1.224 - Looks like I'm not auto-updating?

It was working fine yesterday, so I'll keep an eye out for this issue again (I often remote in).

Thanks!!

**Comment by KirillOsenkov** [comment]
It only auto updates when you start it manually from the Start Menu. If you start it by double-clicking a .binlog file it won't auto-update. 

This is a known bug/limitation: https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/147

Glad the issue is resolved for you. Let me know if you run into anything else.

**Comment by KirillOsenkov** [comment]
If you have this issue, please update to latest.
