### ISSUE TITLE
netstandard2.0 logger version for dotnet on github releases?

### ISSUE THREAD

**Issue by japj** [KirillOsenkov/MSBuildStructuredLog#223]
http://msbuildlog.com/#olderVersions states that for dotnet there is a portable version of the logger in the NuGet package.

I just discovered that this netstandard version is not on the github releases https://github.com/KirillOsenkov/MSBuildStructuredLog/releases
It is only on the nuget package at https://www.nuget.org/packages/MSBuild.StructuredLogger

That is slightly confusing, but I think I understand since the github release is actually only the viewer?
(and a seperate StructuredLogger.dll).

This made me also realize that there are actually nuget packages (with different naming): the logger and the viewer.

Is it possible to add the netstandard logger on the releases page?

**Comment by KirillOsenkov** [comment]
In a GitHub release I'm not sure how to upload two files with the same name (StructuredLogger.dll), and I can't create a separate release with just the binary because it breaks Squirrel (the auto-update library I'm using). So I just edited the last release to contain the netstandard2.0 .dll instead of the net46 .dll. I think it's always safe to use that one instead so this shouldn't break anyone.

Let me know if this solves your problem.

**Comment by KirillOsenkov** [comment]
Note that for most scenarios you shouldn't need this .dll (use `msbuild /bl` to record a .binlog, use the public API in MSBuild to read the .binlog programmatically: https://source.dot.net/#Microsoft.Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs)

**Comment by japj** [comment]
Thanks!
I had the impression that the binlog format has evolved after it was first introduced in msbuild /bl? (And in order to benefit from certain new features I need to use a recent version of structuredlogger.dll)
Anyway, we ran into this issue because a colleague was looking into dotnet msbuild binlog for analysis and he initially could not find the right dll, so it should be ok now.
