### ISSUE TITLE
How to reference logger when added via NuGet

### ISSUE THREAD

**Issue by reidca** [KirillOsenkov/MSBuildStructuredLog#26]
Trying to get this working in our build system as it looks very useful for problem diagnosis. 

We use a CI/CD build server to call MS Build. Since the NuGet package contains the assembly I have not installed the DLL onto the build server, I have added the NuGet package to the VS solution and would to reference it from the project bin location or I'd hope MSBuild would reference it itself. 

The MS Build cmd line we use specifies the file path to the solution file but it does not know the path to the project file where the DLL is. Since the cmd line is shared across multiple builds I cannot hard code a specific path to a participial project.

Is there a way to get MS Build to resolve the reference to the logger from the project file path without having to hard code the path? If not then I do not understand why having this a a nuget package makes sense.

The full cmdline to MS Build I am using is this:

`MSBuild.exe "C:\mypath\mysolution.Api.sln" /nologo /t:Rebuild /p:VisualStudioVersion=12.0 /p:Configuration="Debug" /p:SkipInvalidConfigurations=true /logger:StructuredLogger,StructuredLogger.dll;buildlog1.xml  `

Any help appreciated.

**Comment by KirillOsenkov** [comment]
I'm assuming you have a step such as `nuget restore C:\mypath\mysolution.Api.sln` before calling MSBuild.exe. This will restore the logger .dll to a path like `C:\mypath\packages\Microsoft.Build.Logging.StructuredLogger.1.0.18\lib\net46\StructuredLogger.dll`. Did you try just using the path from packages instead of relying on it being copied to the bin folder of the project?

This way you don't need to know anything about the project that was used to restore the package.

**Comment by reidca** [comment]
I had considered that idea however we are then tied to the version of the package which could update regularly. Is there no way of getting MS Build to resolve the path itself by examining the project files?

**Comment by KirillOsenkov** [comment]
Unfortunately I can't think of anything better (unless you want to write some code/script to search all folders under \packages\Microsoft.Build.Logging.StructuredLogger* and pick the latest one).

The thing is that by the time MSBuild runs, it is too late - you need to pass the logger to MSBuild before it starts. So you can't use any of MSBuild logic to get at the logger .dll.

I think what I proposed above is OK since I only plan to update the logger maybe a couple more times (and then it should stabilize).

**Comment by KirillOsenkov** [comment]
Closing this for now, but please let me know if there's anything I can do to help.
