### ISSUE TITLE
[Feature Request] Add timing information to the tree view

### ISSUE THREAD

**Issue by cuwaters** [KirillOsenkov/MSBuildStructuredLog#27]
It would be very useful to have timing information in the main tree view, so we can see things like which project took the longest, and how much time was spent building dependent projects

**Comment by KirillOsenkov** [comment]
I have timing for how long tasks take, but yes, it'd be very useful to display more detailed timing stats.

**Comment by rahulpnath** [comment]
@KirillOsenkov Did you have anything specific in mind on how to go about this? I can pick this up

**Comment by KirillOsenkov** [comment]
Well, if you look how tasks display their duration grayed out in the node, maybe the same thing for targets and projects. Not sure how useful for projects since projects are built by request from other projects, so not sure how to calculate project exclusive vs. inclusive time.

Also I wanted to manufacture a Folder node at the root level (where we have DoubleWrites for example) and display like top 20 longest targets and top 20 longest tasks (in Message or Proxy node types). Sort of like performance summary view. I think this should be done by the build analyzer (after the actual build log is recorded).

This needs experimenting though.

**Comment by KirillOsenkov** [comment]
I've built a few features around timing.

See the description here: 
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/Timing-and-performance-data
