### ISSUE TITLE
Silverlight 4 SDK is not installed

### ISSUE THREAD

**Issue by MaherJendoubi** [KirillOsenkov/MSBuildStructuredLog#29]
I'm using Silverlight 5 and when I use MSBuild Structured Log Viewer I find this issue:
C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Silverlight.Common.targets(104, 9) : Silverlight 4 SDK is not installed. [XXXX.csproj]

**Comment by MaherJendoubi** [comment]
This is what I have in Microsoft.Silverlight.Common.targets at line 104:

<ValidateSilverlightFrameworkPaths
            TargetFrameworkDirectory = "$(TargetFrameworkDirectory)"
        />

**Comment by MaherJendoubi** [comment]
Even if Silverlight 4 SDK is installed on my PC and my solution is using only Silverlight 5 I still having the issue. FYI: I'm using VS2015 Pro running on Windows 7 SP1 Pro.

**Comment by KirillOsenkov** [comment]
When you normally build your project, what is the command line? Which MSBuild are you using? 12? 14?

**Comment by KirillOsenkov** [comment]
Oh! Could it be because the 64-bit of the app is launching 64-bit MSBuild? When Structured Log Viewer is building your project, it displays the command line (and tells you to use Ctrl+C to copy it). Which MSBuild does it show it will use? 32-bit or 64-bit?

To validate, try building your app with C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe. You should get the same error.

The solution for me would be to provide an option which MSBuild to build with and to default to 32-bit since it's most commonly used.

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/16025629/d5b8a102-31c8-11e6-951c-327ae2e23b63.png)

**Comment by MaherJendoubi** [comment]
@KirillOsenkov I'm using MSBuild 14.0

**Comment by KirillOsenkov** [comment]
Yes, that's what I thought. Should be fixed now, can you try again? I've just pushed the update that uses 32-bit MSBuild always.

**Comment by MaherJendoubi** [comment]
Fixed! Build Succeeded! Thanks a lot @KirillOsenkov :+1:
