### ISSUE TITLE
Create release artifacts for Avalonia version 

### ISSUE THREAD

**Issue by mfilippov** [KirillOsenkov/MSBuildStructuredLog#439]
I want to use this tool on macOS and Windows but now I should build it manually. Could you release Avalonia version tool too?

**Comment by Redth** [comment]
+1 Would love to see this packaged into a proper .app to run on MacOS.

**Comment by eatdrinksleepcode** [comment]
@Redth it looks like you added support for a .app build in #448, including instructions in the README, which include:
> Download the Structured Log Viewer.zip file from the latest Release.
Those instructions are still there; but I can't find the referenced zip file. Am I missing something?

**Comment by KirillOsenkov** [comment]
I think I'd need to publish it next time I'm creating a release?

**Comment by Redth** [comment]
Yeah the artifacts are produced in CI but not uploaded to the GitHub release. Not sure your process for that @KirillOsenkov if it's manual or you automate it somehow. 

Also it would be good to consider setting up a developer account and getting the right certs to sign the app with so that it can be downloaded without unblocking it in preferences and having to manually chmod +x the executable in the bundle. 

Better yet you could publish it to the App Store :)

Feel free to ping me on Teams to chat about this if you like.

**Comment by KirillOsenkov** [comment]
I have set up my Apple Developer account, created a .p12 cert and exported it here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/686#issuecomment-2543403389

Next up we need to figure out how to sign and notarize the app using the cert and create the .dmg

We can use the issue 686, I'm closing this one
