### ISSUE TITLE
Evaluation question: .FindEvaluation() vs. .EvaluationFolder.Children.OfType<ProjectEvaluation>()

### ISSUE THREAD

**Issue by NickCraver** [KirillOsenkov/MSBuildStructuredLog#599]
In writing some tooling based on the lib, I've found many projects to have an EvaluationId of `-1` so `Build.FindEvaluation(id)` doesn't work, but the evaluation is there if I look up via `Build.EvaluationFolder.Children.OfType<ProjectEvaluation>().SingleOrDefault(pe => pe.SourceFilePath == p.SourceFilePath)`. So currently I'm doing:
```cs
var eval = build.FindEvaluation(p.EvaluationId) ?? build.EvaluationFolder.Children.OfType<ProjectEvaluation>().SingleOrDefault(pe => pe.SourceFilePath == p.SourceFilePath);
```

I guess my questions are:
- Is this expected?
- Is there a problem with me going by path as a workaround?

I see this is populated by build context but haven't dug in yet...figured I'd ask if this was expected. If not, happy to dig - I have a consistent repro :)

**Comment by KirillOsenkov** [comment]
If you do File -> Statistics, what's the version of the binlog? And what's the version of MSBuild used? (shown at the top of the binlog)

There was a bug in MSBuild where only projects built in the central node were properly associated with their evaluation Id. Feel free to email me the binlog and I can take a look.

In the latest version it is expected that every project has an evaluation associated with it. Projects can get evaluated several times (depending on the set of properties passed, e.g. evaluating with the property TargetFramework=net472 and TargeFramework=net6.0 will produce two distinct evaluations. So by picking an evaluation just by project path you're picking one at random and it's not clear whether you'll get lucky. It'll be fine most of the time since the bulk of eval results is identical across all evaluations of a project.

**Comment by KirillOsenkov** [comment]
So, regarding missing evaluation ID - could you send me a binlog with that? I want to understand why that instance of Project doesn't seem to have it. You do have the latest version of MSBuild so you shouldn't be impacted by that bug any more.

I think I like the badge for TargetFrameworkVersion as well - I didn't add it purely because I didn't work with legacy projects myself much. If you PR that, that'd be great. No reason to not show this info. Without translation seems fine, as it conveys more information (translating erases the fact that this was legacy).

Don't think people care much about whether the project is legacy or not, and if they do, we can find another way to identify that, perhaps an uglier project icon for legacy projects, or a skull with cross bones, or a radiation sign.

**Comment by NickCraver** [comment]
I had to finish testing a thing before rotating a secret that crept into that binlog but all good now - binlog emailed and #603 open for the badges :)

**Comment by KirillOsenkov** [comment]
Thanks, I think the conclusion for now is that if the project results were satisfied from the cache and the actual build was never invoked, there's no evaluation Id for those projects and we need to filter them out.
