### ISSUE TITLE
Behavior change when running on 9.0.0-preview.7.24405.7

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [KirillOsenkov/MSBuildStructuredLog#817]
I've noticed a behavior change when the tool is running on the .NET 9 preview runtime.

When output task is used, the name of the parameter changes from `<ItemName>` to `<ItemName> from parameter <TaskParameter>`.

For example, we can have a .csproj file in the following form:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Test">
        <XmlPeek XmlInputPath="test.xml"
                 Query="//s:variable/@Name"
                 Namespaces="&lt;Namespace Prefix='s' Uri='http://nsurl' /&gt;">
            <Output TaskParameter="Result" ItemName="ResultOutput" />
        </XmlPeek>
    </Target>
</Project>
```
When running on an older runtime (like 6.0) the parameter is named `ResultOutput` 
 
![image](https://github.com/user-attachments/assets/2a339244-0f87-4085-8fc9-009196e69c8e)

On the other hand when running on .NET 9.0.0-preview.7.24405.7, the parameter is named `ResultOutput from parameter Result`

![image](https://github.com/user-attachments/assets/513114b2-47c8-4062-8f9c-1ea682c2ac5a)

You can find here the sources of the reproducer: [reproducer.zip](https://github.com/user-attachments/files/16993773/reproducer.zip)

I used a `global.json` file to change the runtime.

**Comment by KirillOsenkov** [comment]
@JanKrivanek any quick guess what might have changed in MSBuild?

**Comment by KirillOsenkov** [comment]
it's a good change (it gives more info), need to think whether to present it slightly differently in the viewer

btw love great bug reports! detailed and with a minimal repro!

**Comment by costin-zaharia-sonarsource** [comment]
> btw love great bug reports! detailed and with a minimal repro!

Thanks, @KirillOsenkov! I like the MSBuildStructuredLog tool and I find it very useful.

> it's a good change (it gives more info), need to think whether to present it slightly differently in the viewer

On our side, we are more affected by this change when we're using the library since now `BinaryLog.ReadBuild(filePath).VisitAllChildren<Property>(x => ..)` returns slightly different values.  Nothing major though.

**Comment by JanKrivanek** [comment]
Thanks for report and thanks for tagging me here.

@ladipro was working on improving and neriching the info around task parameters:
 * https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/780
 * https://github.com/dotnet/msbuild/pull/10130

It's comming from the first one.

To me this honestly feels as pure improvement.
Being dependent on specific order on the other hand feels too rigid to allow improving changes.
I might have very oversimplified PoV due to lack of knowledge of the specific scenario. If it would feel apropriate to accomodate the scenario, please try to elaborate more.

**Comment by KirillOsenkov** [comment]
I guess perhaps we can parse the message and just keep the item name as earlier, but add the parameter mapping on the side somewhere, because now the item name is not really the item name so analyzers looking for $additem for rxample won't match this. I can look later to see if I have ideas on how to represent this better.

**Comment by JanKrivanek** [comment]
Or this change can be reverted:

https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/780/files#diff-c24cc7981706583e29dbaa574cfa45c811c418166d928225844132d8425c993aL196-R203

or applied just as a tooltip or so.

I'm happy to adjust this next week - just lm know

**Comment by KirillOsenkov** [comment]
Yes, I think we need to change this somehow and expose this information in a different way. The item name should be just item name.

**Comment by lambdageek** [comment]
👍 on adding some more structure around this (maybe a subclass of AddItem for output items?)

FYI i'm working on a little tool that parses a binlog and creates a .proj that re-runs some selected tasks (https://github.com/lambdageek/monostump) an `{item} from parameter {paramName}` makes it tough to roundtrip a binlog into a project file

**Comment by KirillOsenkov** [comment]
How's this?

![image](https://github.com/user-attachments/assets/b3ab7136-aa05-49fc-b2b9-9553d83d93d1)

**Comment by KirillOsenkov** [comment]
Published 
 * https://github.com/KirillOsenkov/MSBuildStructuredLog/releases/tag/v2.2.350
 * https://www.nuget.org/packages/MSBuild.StructuredLogger/2.2.350
 * https://www.nuget.org/packages/binlogtool/1.0.18
