### ISSUE TITLE
Display timestamp in logger messages

### ISSUE THREAD

**Issue by jdom** [KirillOsenkov/MSBuildStructuredLog#835]
Hi, is there a way to show the timestamp on each of the emitted messages within a task? I'm troubleshooting a race condition inside a complex msbuild task that emits a lot of output, and it would be good to have this info, which I know it's part of the binlog, but it's just not being displayed in the UI by default (at least I couldn't find it)

**Comment by KirillOsenkov** [comment]
I made it so that all messages under tasks are displayed with a timestamp:
![image](https://github.com/user-attachments/assets/d9e7cdd3-a793-411a-860f-7881529478b1)

I haven't deployed this yet. If this is still relevant, can you build the project from source, try it out and let me know if this works OK for you?

Also see if any of the features mentioned here can help:
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/Timing-and-performance-data

Perhaps we can make `$start > ` etc. queries work to filter out messages in a particular timespan?

**Comment by KirillOsenkov** [comment]
This is now shipped in 2.2.392

**Comment by jdom** [comment]
Thank you! This looks great! Sorry I was not able to verify it sooner
